services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wp_db
    secrets:
      - mysql_password
      - mysql_root_password

  wordpress:
    container_name: wordpress
    build: ./wordpress
    image: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_db
      - nginx_vol
    depends_on:
      - mariadb
    secrets:
      - wordpress_password
      - wordpress_admin_password
      - mysql_password
      - mysql_root_password
    

  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - nginx_vol
    depends_on:
      - wordpress

networks:
  nginx_vol:
    driver: bridge
  wp_db:
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kali/data/mariadb
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kali/data/wordpress
      #       - db_data:/var/lib/mysql

secrets:
  mysql_password:
    file: ../secrets/mysql_password
  mysql_root_password:
    file: ../secrets/mysql_root_password
  wordpress_password:
    file: ../secrets/wordpress_password
  wordpress_admin_password:
    file: ../secrets/wordpress_admin_password
  
    