
server {
    listen 80;
    server_name dgermano.42.fr;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Proxy para o site da 42
    location /intra {
        proxy_pass https://42.fr;
        proxy_set_header Host 42.fr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # PHP-FPM
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9001;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Bloquear ficheiros ocultos (.htaccess, .htpasswd)
    location ~ /\. {
        deny all;
    }
}
