
server {
    listen 443 ssl;
    server_name dgermano.42.fr;

    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    
    root /var/www/html;
    index index.php;

    location /intra {
        return 301 https://42.fr;
    }
    
    location ~ \.php$ {
        try_files $uri =404;
        
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        
        # Importante: certifique-se que o caminho no container PHP é o mesmo
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Bloquear ficheiros ocultos (.htaccess, .htpasswd)
    # location ~ /\. {
    #     deny all;
    # }
}
