
# server {
#     listen 80 ;
#     server_name dgermano.42.fr;

#     root /var/www/html;
#     index index.php;

#     location /intra {
#         return 301 https://42.fr;
#     }
    
#     location / {
#         try_files $uri $uri/ =404;
#     }

#     # Proxy para o site da 42


#     location ~ \.php$ {
#         root /var/www/html;
#         include fastcgi.conf;
#         fastcgi_pass wordpress:9000;
#     }

#     # Bloquear ficheiros ocultos (.htaccess, .htpasswd)
#     # location ~ /\. {
#     #     deny all;
#     # }
# }
